# Buildpacks to include in builder
[[buildpacks]]
uri = "../../buildpacks/quarkus-native-buildpack"

[[order]]
    [[order.group]]
    id = "io.quarkus.native.buildpack"
    version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.quarkus.native"
run-image = "redhat/quarkus-stack-run:native"
build-image = "redhat/quarkus-stack-build:native"

